# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"@\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x0fGetUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\")\n\x12\x43reateUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"A\n\x11UpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\")\n\x12UpdateUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x08UserList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User2\x9c\x02\n\x0bUserService\x12.\n\x07GetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\"\x00\x12\x37\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\"\x00\x12\x37\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\"\x00\x12\x37\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\"\x00\x12\x32\n\x0bGetAllUsers\x12\x16.google.protobuf.Empty\x1a\t.UserList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=43
  _globals['_USER']._serialized_end=90
  _globals['_POST']._serialized_start=92
  _globals['_POST']._serialized_end=156
  _globals['_GETUSERREQUEST']._serialized_start=158
  _globals['_GETUSERREQUEST']._serialized_end=191
  _globals['_GETUSERRESPONSE']._serialized_start=193
  _globals['_GETUSERRESPONSE']._serialized_end=231
  _globals['_CREATEUSERREQUEST']._serialized_start=233
  _globals['_CREATEUSERREQUEST']._serialized_end=281
  _globals['_CREATEUSERRESPONSE']._serialized_start=283
  _globals['_CREATEUSERRESPONSE']._serialized_end=324
  _globals['_UPDATEUSERREQUEST']._serialized_start=326
  _globals['_UPDATEUSERREQUEST']._serialized_end=391
  _globals['_UPDATEUSERRESPONSE']._serialized_start=393
  _globals['_UPDATEUSERRESPONSE']._serialized_end=434
  _globals['_DELETEUSERREQUEST']._serialized_start=436
  _globals['_DELETEUSERREQUEST']._serialized_end=472
  _globals['_DELETEUSERRESPONSE']._serialized_start=474
  _globals['_DELETEUSERRESPONSE']._serialized_end=511
  _globals['_USERLIST']._serialized_start=513
  _globals['_USERLIST']._serialized_end=545
  _globals['_USERSERVICE']._serialized_start=548
  _globals['_USERSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
